version: '3.9'

services:
  producer:
    build: ./producer
    ports:
      - "5000:5000"
  rabbitmq:
    image: "rabbitmq:3.9-management"
    ports:
      - "15672:15672"
      - "5672:5672"
  consumer:
    build: ./consumer
    volumes:
      - type: bind
        source: ./output
        target: /app/output